import { createElement } from 'lwc';
import DispatchingContainer30to34 from 'c/dispatchingContainer30to34';

describe('c-dispatching-container30-to34', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-dispatching-container30-to34', {
            is: DispatchingContainer30to34
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});